import{a as y,S as v,i as n}from"./assets/vendor-D8kWkXeg.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function L(i){return y.get("https://pixabay.com/api/",{params:{key:"55036420-a7a19d5751e273048ff10c958",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const d=document.querySelector(".gallery"),m=document.querySelector(".loader");let w=new v(".gallery .photo-card a",{captionsData:"alt",captionDelay:250});function b(i){function r(e){const{webformatURL:t,tags:a,likes:f,views:u,comments:h,downloads:p,largeImageURL:g}=e;return`<div class="photo-card">
              <a href=${g}><img src="${t}" alt="${a}"/></a>

              <div class="info">
              <div class="info-item"><h2>Likes: <span>${f}</span></h2></div>
              <div class="info-item"> <h2>Views: <span>${u}</span></h2></div>
              <div class="info-item"><h2>Comments: <span>${h}</span></h2></div>
              <div class="info-item"><h2>Downloads: <span>${p}</span></h2></div>
            </div>
            </div>`}function s(e){return e.map(r).join("")}const o=s(i);d.innerHTML=o,w.refresh()}function S(){d.innerHTML=""}function D(){m.classList.remove("is-hidden")}function c(){m.classList.add("is-hidden")}const l=document.querySelector(".form");l.addEventListener("submit",$);function $(i){i.preventDefault();const s=new FormData(l).get("search-text");if(s.trim()===""){n.show({message:"Please enter a search term",position:"topRight"});return}else S(),D(),L(s).then(o=>{o.hits.length?b(o.hits):(c(),n.show({message:"Sorry, there are no images matching your search query.Please try again!",position:"topRight"}))}).catch(o=>{c(),n.error({message:"Something went wrong!",position:"topRight"})}).finally(()=>{c(),l.reset()})}
//# sourceMappingURL=index.js.map
