import{a as g,S as y,i as n}from"./assets/vendor-D8kWkXeg.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function v(s){return g.get("https://pixabay.com/api/",{params:{key:"55036420-a7a19d5751e273048ff10c958",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const l=document.querySelector(".gallery"),d=document.querySelector(".loader");let L=new y(".gallery .photo-card a",{captionsData:"alt",captionDelay:250});function w(s){function r(e){const{webformatURL:t,tags:a,likes:m,views:u,comments:f,downloads:h,largeImageURL:p}=e;return`<div class="photo-card">
              <a href=${p}><img src="${t}" alt="${a}"/></a>

              <div class="info">
              <div class="info-item"><h2>Likes: <span>${m}</span></h2></div>
              <div class="info-item"> <h2>Views: <span>${u}</span></h2></div>
              <div class="info-item"><h2>Comments: <span>${f}</span></h2></div>
              <div class="info-item"><h2>Downloads: <span>${h}</span></h2></div>
            </div>
            </div>`}function i(e){return e.map(r).join("")}const o=i(s);l.innerHTML=o,L.refresh()}function b(){l.innerHTML=""}function S(){d.classList.remove("is-hidden")}function D(){d.classList.add("is-hidden")}const c=document.querySelector(".form");c.addEventListener("submit",$);function $(s){s.preventDefault();const i=new FormData(c).get("search-text");if(b(),S(),i.trim()===""){n.show({message:"Please enter a search term",position:"topRight"});return}else v(i).then(o=>{o.hits.length?w(o.hits).catch(e=>n.error({message:"Something went wrong!"})):n.show({message:"Sorry, there are no images matching your search query.Please try again!",position:"topRight"})});D(),c.reset()}
//# sourceMappingURL=index.js.map
